### ISSUE TITLE
[feature request] configurable swipes

### ISSUE THREAD

**Issue by ztNFny** [lwis/HeadsUpHide#1]
Hi,
it'd be great to have some swipes (e.g. left+right) dismiss and others (up) hide the notifications.
Even greater if it was configurable :-)

**Comment by lwis** [comment]
Not easily achievable, and this is my first time using Xposed so I'm a
little rough.

I did initially look into this, but ended up settling on this as a v1. I'll
spend some time investigating how this could be possible over the week.

**Comment by ztNFny** [comment]
Thanks. It's highly appreciated (both the module as is as well as you looking into this request).

**Comment by nisargkolhe** [comment]
+1 for the feature request. And thanks for the awesome module! :)

**Comment by lwis** [comment]
Just published a new version, could you install and let me know if there's any issues?

**Comment by ztNFny** [comment]
Works good, no issues so far

**Comment by ztNFny** [comment]
SystemUI FC when I swipe to dismiss, swipe to hide is ok.
Left/right is set to dismiss, up to hide. Xposed alpha 2,  cm-12-20150308-NIGHTLY-mako.zip.
Logcat:
E/AndroidRuntime(12513): FATAL EXCEPTION: main
E/AndroidRuntime(12513): Process: com.android.systemui, PID: 12513
E/AndroidRuntime(12513): java.lang.NoSuchMethodError: com.android.systemui.statusbar.phone.PhoneStatusBar#onHeadsUpDismissed()#bestmatch
E/AndroidRuntime(12513):        at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:271)
E/AndroidRuntime(12513):        at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:284)
E/AndroidRuntime(12513):        at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:947)
E/AndroidRuntime(12513):        at com.lewisjuggins.headsuphide.ModHeadsUp$2.replaceHookedMethod(ModHeadsUp.java:110)
E/AndroidRuntime(12513):        at de.robv.android.xposed.XC_MethodReplacement.beforeHookedMethod(XC_MethodReplacement.java:15)
E/AndroidRuntime(12513):        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:636)
E/AndroidRuntime(12513):        at com.android.systemui.statusbar.policy.HeadsUpNotificationView.onChildDismissed(Unknown Source)
E/AndroidRuntime(12513):        at com.android.systemui.SwipeHelper$2.onAnimationEnd(SwipeHelper.java:351)
E/AndroidRuntime(12513):        at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1089)
E/AndroidRuntime(12513):        at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:666)
E/AndroidRuntime(12513):        at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:682)
E/AndroidRuntime(12513):        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
E/AndroidRuntime(12513):        at android.view.Choreographer.doCallbacks(Choreographer.java:580)
E/AndroidRuntime(12513):        at android.view.Choreographer.doFrame(Choreographer.java:549)
E/AndroidRuntime(12513):        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
E/AndroidRuntime(12513):        at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(12513):        at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(12513):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(12513):        at android.app.ActivityThread.main(ActivityThread.java:5256)
E/AndroidRuntime(12513):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12513):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(12513):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
E/AndroidRuntime(12513):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
E/AndroidRuntime(12513):        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
W/DropBoxManagerService(  555): Dropping: system_app_crash (2042 > 0 bytes)

**Comment by lwis** [comment]
Are you on CyanogenMod? Use v1.2.

**Comment by ztNFny** [comment]
Was using 1.1, 1.2 seems to fix it.
For some reason Xposed Manager doesn't show updates to this module in the module list but only in the module details so I didn't see 1.2 as available.

**Comment by lwis** [comment]
It was experimental, I just changed it to stable - that's likely to be why
you missed it.
