### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by Syl0s** [lwis/HeadsUpHide#2]
I'm trying to use your module on CyanogenMod11 M12. Which is still KitKat, but already allowed Heads-Up Notifications to be enabled.
Now, is your module only for Lollipop, or is it an error, that it tells me that your module's APK is not compatible?

**Comment by lwis** [comment]
I'm not sure what the KitKat implementation looks like, but it's never been
tested to work on CM11.

**Comment by Syl0s** [comment]
As far as I can tell, the KitKat-implementation is pretty much the same. At least it doesn't look any different at all.
Heads-Up Notifications are actually a pretty old feature of Android...
The only change in Lollipop, that I know of, comes with version 5.1 and essentially does exactly what your module does.
But yeah, if I might try to simply recompile your module with a lower SDK-version and see if it works for me.

**Comment by lwis** [comment]
Go ahead, if it works then feel free to creae a PR and I'll merge it.

**Comment by Syl0s** [comment]
Ok, I've lowered the minSDK-version to 19 and could install it on my phone. The GUI opens up normally, but the XPosed Bridge on my phone is out of date compared to the one that you used (since it's obviously not the XPosed Bridge for Lollipop).
So, as is, I can't really test it either.
Not sure, how to downgrade the XPosed Bridge in your module, or if that is even possible. Or if it's possible to upgrade mine without breaking things...

**Comment by lwis** [comment]
You can lower the minimum version in the manifest.

**Comment by Syl0s** [comment]
Ah, now I can enable it. But yeah, doesn't seem to work. Swiping up doesn't respond in any way, and swiping left or right does the usual thing. It's basically, as if I would've never even enabled the module. A shame, but I suppose, there's not much that one can do about it then, without rewriting the entire module...

**Comment by lwis** [comment]
If you point me to the source tag on the GitHub mirror, I'll take a look.

**Comment by Syl0s** [comment]
If you want that, then you'll have to bear with me here.
I'm pretty much a complete noob, concerning GitHub. I have worked with GIT before, but not on an open source project, and neither really for an extended period of time.
I've so far only pulled from your repository and made the changes locally.
I didn't fork, commit, push or tag anything. At least not knowingly. Maybe pulling it automatically created a branch for me or something like that.
How would I go from here to create such a tag and have it publicly visible for you?
I would guess commit->push->create tag, but even if that's correct, I have no clue.
Otherwise, I could also just tell you the changes that I made. It's like 4 steps to get to where I am now...

**Comment by lwis** [comment]
I think I know what changes you've made, I'm referring to the tag of AOSP
you're on @ https://github.com/android/platform_frameworks_base

**Comment by Syl0s** [comment]
Oh, I'm on android-4.4.4_r2. Or Build-Number KTU84Q.

**Comment by lwis** [comment]
@Syl0s Take a look at the differences between these two files;

https://github.com/android/platform_frameworks_base/blob/android-4.4.4_r2.0.1/packages/SystemUI/src/com/android/systemui/statusbar/policy/HeadsUpNotificationView.java

https://github.com/android/platform_frameworks_base/blob/android-5.0.2_r1/packages/SystemUI/src/com/android/systemui/statusbar/policy/HeadsUpNotificationView.java

My implementation is based on the latter, and I'm replacing methods. You could fork for different Android version implementations (like I have for Cyanogen) for backwards compatibility.
